### ISSUE TITLE
Multiple Middle-Earth Repositories

### ISSUE THREAD

**Issue by Hukoseft** [BSData/middle-earth#104]
I have created a repository for Middle-Earth Strategy Battle Game, it is complete (aside from extra's) however I am unsure of how to get it on the list of repositories available for people to easily download from inside the app.

https://github.com/Hukoseft/Middle-Earth-SBG is the location of the files

**Comment by Zhaph** [comment]
Thanks for your work updating the repo @Hukoseft I've added the accents back in, and created release 2.0.0 with your files - here's to Gondor at War and beyond!
