### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by pwojewodzic** [BSData/middle-earth#105]
I want to add some new armies to BSData among others my Iron Hill Dwarves 😉

**Comment by Hukoseft** [comment]
@pwojewodzic if you take note, all armies have been added now :)

**Comment by Zhaph** [comment]
Apologies for the delay in getting back to you @pwojewodzic we'd just had a wonderful offer from @Hukoseft to use their complete files - as such I was waiting until we'd finished pulling those in and released them before we added more contributors.

I hope you find the new files useful! If you're still interested in helping out if any issues are found, then do please let us know :)
