### ISSUE TITLE
The Rangers - Dúnedain hero selection in wrong place.

### ISSUE THREAD

**Issue by Zhaph** [BSData/middle-earth#115]
The following issue was noted in The Rangers army list:

- Dúnedain's "Independent Hero" option should be under the Dúnedain model, not the Dúnedain group  
![image](https://user-images.githubusercontent.com/1271482/51444894-e66d5180-1cf5-11e9-9ca6-965b4c85df28.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a roster with 'The Rangers'
2. Add selections of 'Dúnedain'

**Game System (please complete the following information):**
 - Game System Version: 53
 - Catalogue Name and Version: The Rangers v 7

**Additional context**

**Comment by Zhaph** [comment]
Sorry - was changing forces which removed the Misc selection that had been added but doesn't add the new one. I'll create new rosters going forwards.

**Comment by Hukoseft** [comment]
Independant hero is there because they are a minor hero in The Shire list. All heroes which have different levels in different lists have it this way. It is to save users from having to manually remove the level they aren't if I have both with modifiers
