### ISSUE TITLE
Hobbit Warriors Missing

### ISSUE THREAD

**Issue by M-J-Hastings** [BSData/middle-earth#142]
The army lists ported from the Hobbit BSData (which I created) are missing the Warriors/only displaying the Heroes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a roster with Moria or Rivendell, or other lists from the Hobbit BSData.
2. Add selections of Heroes or Misc, but nowhere can I choose Warriors.

**Expected behavior**
Another section of Warriors, distinct from Heroes.

**Game System (please complete the following information):**
 - Game System Version: 2.1.0
 - Catalogue Name and Version: Moria v12, Rivendell v21, possible/probably all the others ported from Hobbit BSData

**Additional context**
Happy to help out with this issue or other fixes if needed.

**Comment by Hukoseft** [comment]
Hi,

There are warbands in each hero to add the Warriors, this is the expected behavior.

These files are different from the Hobbit files which have existed in the past.
