### ISSUE TITLE
[Anon] Bug report: Halls_of_Thranduil.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/middle-earth#188]
**File:** Middle-Earth_Strategy_Battle_Game.gstz

**BattleScribe version:** 2.03.17

**Platform:** Android

**Dropbox:** No

**Description:** Middle Earth Halls of Thranduil - Mirkwood Rangers aren't supposed to count towards the armies bow count but is saying that I am over my bow limit (limit of 0)

**Comment by Hukoseft** [comment]
Add the army bonus and this works

**Comment by Hukoseft** [comment]
Army bonus is not allowing mirkwood rangers to not count towards bow Limit

**Comment by Hukoseft** [comment]
Fixed in version I am working on, to be released with other changed
