### ISSUE TITLE
[Anon] Bug report: Fangorn.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/middle-earth#191]
**File:** Fangorn.catz

**BattleScribe version:** 2.03.10

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** New profiles for beechbone and quickbeam aren’t updated or on the app at all

**Comment by Hukoseft** [comment]
Updated file didn't get correctly merged prior to release. It is ready to go with the next one.
