### ISSUE TITLE
Bug report: The_Kingdom_of_Khazad_Dum.catz

### ISSUE THREAD

**Issue by ChronosDarkhelmet** [BSData/middle-earth#198]
When loading the catalogue, all hero tiers appear as "Uncategorised" instead of the relevant tiers. This issues lots of warnings during the army list creation.

**Comment by Hukoseft** [comment]
Cannot replicate error, can you please provide screenshots as well as version number for both the system and the kingdom of khazad dum catalogue

**Comment by ChronosDarkhelmet** [comment]
Roster Editor version: 2.03.14
Catalogue version: 14
OS version: macOS High Sierra 10.13.6

This is what I get when loading the catalogue:
![bs_screenshot_khazaddum](https://user-images.githubusercontent.com/12880179/78367786-edaf1100-75c2-11ea-99f5-a389b05ccb1e.png)

Note that, for a number of reasons, I cannot update my OS to more recent versions.

**Comment by Hukoseft** [comment]
Update your catelogue to the most recent one. It should be version 18.
