### ISSUE TITLE
The Grey Company LL - Anduril is not free

### ISSUE THREAD

**Issue by Lionic1** [BSData/middle-earth#212]
Just a small error in the Grey Company Legendary Legion where Anduril is supposed to be free 
(Images included)

![image_2021-01-12_093625](https://user-images.githubusercontent.com/77325872/104296543-a5aa0c80-54b9-11eb-979f-160ac22f91eb.png)
![image_2021-01-12_093656](https://user-images.githubusercontent.com/77325872/104296587-b8244600-54b9-11eb-9faf-6ceac7eedc9b.png)
![image_2021-01-12_093716](https://user-images.githubusercontent.com/77325872/104296614-c4100800-54b9-11eb-9cff-5faf9ed15367.png)

**Comment by Hukoseft** [comment]
Thanks, it also has shown a bug that The grey company isn't marked as a Legendary Legion either
