### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by MJHastings** [BSData/middle-earth#235]
Hello there, I worked on the Hobbit data a few years ago and would like to make so corrections to typos and other small things in Middle Earth. - Easier for me to do it myself than have to put up issues.

How do I go about getting permission to make releases?

**Comment by Hukoseft** [comment]
Hi,

We're not looking for contributers at this time. Especially since the main Battlescripe app isn't being updated anymore.

**Comment by MJHastings** [comment]
Oh, so it’ll become buggy with new OS updates?

**Comment by Hukoseft** [comment]
No idea, there are people workong on an alternative which will read them all similarily.
