### ISSUE TITLE
Garrison of Dale: Legendary Legion Bug

### ISSUE THREAD

**Issue by Zorak1987** [BSData/middle-earth#257]
When you try to choose the legendary legion of Garrison of Dale, It does not load all the characters to be able to make the list, or rather, no characters load, it is as if it did not exist.

PC version

**Comment by Hukoseft** [comment]
Hi,

Can you please provide screenshots.

**Comment by Zorak1987** [comment]
I am sending you the screenshots, I have circled the errors, when you
choose the legendary legion, the roster does not update, only the
characters of Dale remain, the Dwarves of the legendary legion do not come
out to compose the legion.

Il giorno sab 22 ott 2022 alle ore 06:01 Hukoseft ***@***.***>
ha scritto:

> Hi,
>
> Can you please provide screenshots.
>

**Comment by Hukoseft** [comment]
In order to add the dwarves for the combined Legendary Legion "Defenders of Erebor" you need to have both catelogues Garrison of Dale & Erebor Reclaimed.

As for hiding certain heroes, will look into that.
