### ISSUE TITLE
Minas Tirith - Gondor Bolt Thrower bad warrior count

### ISSUE THREAD

**Issue by pieplu** [BSData/middle-earth#258]
Since few designer corrections, the number of warrior included with the Gondor Bolt Thrower is 3 (and not 2, like the first edition of the army list say)

Thanks in advance :)

**Comment by Hukoseft** [comment]
Hi,

The number of models included is 3, 1 is Siege Veteran, 2 are Warriors.

**Comment by pieplu** [comment]
Ho! Thanks for the quick response, my bad.
