### ISSUE TITLE
Getting Error when creating a Gondor Roster. (Roster) has too many selections of Aragorn, King Elessar.

### ISSUE THREAD

**Issue by LRavenheart** [BSData/middle-earth#269]
When I add Boromir to the safe roster as Aragorn, this error crops up. I have tested it on several roster configurations to the same result.

**Comment by Hukoseft** [comment]
As per the Errata Aragorn, King Elessar may not be included in the same force as either Boromir, Captain of the White Tower, Boromir of Gondor nor Denethor, Steward of Gondor.

If you wish to send screenshots to show cases other than those listed above it would make it easier.
