### ISSUE TITLE
RES and SSE categories missing

### ISSUE THREAD

**Issue by CaptainGelb** [BSData/middle-earth#276]
The datefile has no primary categories to the RES or SSE entries. 
Due to this New Recruit App can't display any units to add. 

On the pictures you can see that there are no units on display to add to the roster. 

Past iterations had this entries. 
![Screenshot_20230924_153059_Chrome](https://github.com/BSData/middle-earth/assets/55626118/8f679172-1791-448a-a011-64d994b94051)
![Screenshot_20230924_153052_Chrome](https://github.com/BSData/middle-earth/assets/55626118/295c2335-f90e-46ff-93cd-b1cc9a2b159d)

**Comment by giloushaker** [comment]
It's not a data issue, an error is preventing the add unit panel from showing.

**Comment by Hukoseft** [comment]
Closing this issue as it is from NewRecruit's end and nothing to do with us (they just use our files)
