### ISSUE TITLE
Node has no name

### ISSUE THREAD

**Issue by giloushaker** [BSData/middle-earth#284]
**Describe the bug**
Node has no name

**Location:**
Mordor > Warband > Wargear 
ID: bce7-fa7b-86c2-096f

**Game System (please complete the following information):**
 - Game System Version: 112
 - Catalogue Name and Version: Mordor v29

**Comment by giloushaker** [comment]
Theres 25 of these, is it intended?
![image](https://github.com/BSData/middle-earth/assets/55761672/4decf902-811e-445a-88c7-4aedbfbf6d28)

**Comment by Hukoseft** [comment]
Hi,

Not sure what you're asking. It is for options where there is no need to add extra text. The output is already full enough.
