### ISSUE TITLE
[Anon] The Rangers: Warband options for Halbarad and Aragorn do not work properly stuck at 1 ranger or Dunedain

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/middle-earth#288]
**Problem:**
Warband options for Halbarad and Aragorn do not work properly stuck at 1 ranger or Dunedain

**Expected:**
Ability to include more than one of each in warband

**List:** https://www.newrecruit.eu/app/list/Fd7oe

**Comment by Hukoseft** [comment]
This works fine in Battlescribe, therefore the issue must be on the NewRecruit side of things, contact them on their discord
