### ISSUE TITLE
[Anon] Variags of Khand: Wargear is not displayed next to the correct warriors, instead it is displayed next to the ones above them; this is a problem with all MESBG data apparently, not just one or two armies. The points appear to be correct, but the display is confusing.

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/middle-earth#290]
**Problem:**
Wargear is not displayed next to the correct warriors, instead it is displayed next to the ones above them; this is a problem with all MESBG data apparently, not just one or two armies. The points appear to be correct, but the display is confusing.

**Expected:**
Wargear should be displayed next to each group of warriors (ones with bows should show bows next to them, etc.)

**List:** https://www.newrecruit.eu/app/list/TWJk3

**Comment by Hukoseft** [comment]
This is a NewRecruit issue, not a data issue. We are unable to solve it on our end. Try their discord.
