### ISSUE TITLE
[Anon] Minas Tirith: Frodo Sam and Smeagol automatically counted in Faramirs Warband. Can be taken as independent but gives an error 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/middle-earth#291]
**Problem:**
Frodo Sam and Smeagol automatically counted in Faramirs Warband. Can be taken as independent but gives an error 

**Expected:**
Independent hero inclusion of the hobbits and Smeagol 

**List:** https://www.newrecruit.eu/app/list/csyTP
**Unit:** Faramir, Captain of Gondor, id: 8a48-8f51-579b-2aa2

**Comment by Hukoseft** [comment]
This appears to be an issue in New Recruit only, please refer to their discord.
