### ISSUE TITLE
[Anon] Minas Tirith: When including hobbits as independent hero choice samwise is read as 1/0 when included 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/middle-earth#292]
**Problem:**
When including hobbits as independent hero choice samwise is read as 1/0 when included 

**Expected:**
Samwise is allowed with Frodo in an independent group 

**List:** https://www.newrecruit.eu/app/list/9oLHk
**Unit:** Hobbits, id: 9ad6-7767-234c-3602

**Comment by Hukoseft** [comment]
This appears to be an issue with New Recruit, please refer to their discord.
