### ISSUE TITLE
[Anon] Dark Denezins of Mirkwood: The Spider Queen has 9 selections too many of Warband (max 1)


### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/middle-earth#293]
**Problem:**
The Spider Queen has 9 selections too many of Warband (max 1)

**Expected:**
Her to have one warband

**List:** https://www.newrecruit.eu/app/list/W1h7a
**Unit:** The Spider Queen, id: ec58-9c75-31fd-e8a3

**Comment by Hukoseft** [comment]
Based on what the error states, you have somehow copied the Warband entry, not added specific warriors to the warband.

If your intention was to have extra warbands with just warrior models, you need to add the army bonus and that will allow warrior warbands.

**Comment by Hukoseft** [comment]
![Screenshot_20241230_111332_Chrome](https://github.com/user-attachments/assets/bed95e45-6a4d-4da5-8f79-19b3e4988fd7)
![Screenshot_20241230_111705_Chrome](https://github.com/user-attachments/assets/82a5e147-3371-4158-bbb7-e0f2c3d5777e)

Tapping on the tick here will remove all warbands, tapping on it again will add a sinlge one (must always have a warband, even if it is empty)
