### ISSUE TITLE
Create Shared Selections for all Hobbit Army Lists

### ISSUE THREAD

**Issue by cordwartman** [BSData/middle-earth#62]
There are a number of Shared Model profiles across the Hobbit Armies, Azog, Gandalf, Bard etc. 
These should be created and merged before the main Army lists are created to prevent double work

**Comment by cordwartman** [comment]
This should be all the Shared Entry links. Some of Shared Entries were already created in the LotR update, like Fell Wargs and Ori and Oin

Gandalf
Bard
Sigrid and tilda
Bain
Azog
Bolg
Alfrid
Dain 
Iron Hills Captain
Iron Hills Dwarf
Iron Hills Goat rider
Radagast
The White Warg
Hunter ORc
Hunter Orc Captain
Gundabad Orc Captain
Gundabad Orc
Mirkwood spider
Giant spider
Goblin Mercenary captain
Goblin Mercenary

**Comment by Zhaph** [comment]
The following will need to be moved into the main file:

* Wood Elf Sentinel
* Gwaihir
* Great Eagle
* Glorfindel
* Celeborn

**Comment by Zhaph** [comment]
I've moved the above entries into the main file and updated Rivendell, Lothlorien and The Misty Mountains in master, and merged into Armies of the Hobbit Feature in advance of the other files.
