### ISSUE TITLE
First Round of Release fixes 

### ISSUE THREAD

**Issue by cordwartman** [BSData/middle-earth#78]
Dwarf ballista in Khazadum is 8 points too much should be 60

the mordor siege engines additional crew are free when they should be 5pts.

~~Roll off for elven blades are 1-4 evil/3-6 good when they should be 1-2 evil/3-6 good.~~ Added further clarity to the wording

~~Knights of Minas Tirith shields cost 5 pts instead of 1~~ Done

~~Shield rules needs to be checked (says spear applies to cumbersome)~~ Removed Spear, added Crossbow. Updated additional restriction to note that Hand-and-a-half weapons will reduce the modifier if used two handed.

~~Gothmog needs the Leader~~ Done

**Comment by Zhaph** [comment]
Nazgul fixed in #88 
Seige Engines fixed in #82
