### ISSUE TITLE
Dead of Dunharrow Army bonus 

### ISSUE THREAD

**Issue by cordwartman** [BSData/middle-earth#79]
Dead of Dunharrow captain bonus needs to be adjusted so it doesn't throw a hero error.

Maybe copy the wild men version

**Comment by Zhaph** [comment]
I'm not sure I know what the error is - if I add seven warriors (mix of Warrior and Rider) then I can add a Rider or Warrior (Captain) as the eighth model. This is in keeping with rule:

> that contain 8 or more models

Where as the Wildmen is explicitly 9-12.

**Comment by Zhaph** [comment]
I believe this is working as intended. Will reopen if required.
