### ISSUE TITLE
[Anon] Bug report: Middle_Earth_Strategy_Battle_Game.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/middle-earth#89]
**File:** Middle_Earth_Strategy_Battle_Game.gstz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The watchers of karna have to pay 5 points for bows and poison arrows. They should be free.

**Comment by Zhaph** [comment]
Closing as a duplicate of #90 (that has the right file).
