### ISSUE TITLE
[Anon] Bug report: The_Serpent_Horde.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/middle-earth#90]
**File:** The_Serpent_Horde.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Watchers of Karna are supposed to choose bow or dual blades for free. The bows cost 5 points in the app

**Comment by Zhaph** [comment]
Duplicated by #89
